name: Deploy to GitHub Pages

on:
  workflow_dispatch: {}    
  push:
    branches: ["main"]      

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ghp
      url: ${{ steps.deploy-ghp.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Setup GitHub Pages
      #   uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: ghp
          path: ./  

      - name: Deploy to GitHub Pages
        id: deploy-ghp
        uses: actions/deploy-pages@v4
        with:
          artifact_name: ghp
